[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.19'
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'solady/=lib/solady/',
  'seaport-core/=lib/seaport-core/',
  'seaport-sol/=lib/seaport-sol/',
  'seaport-types/=lib/seaport-types/',
  'shipyard-core/=lib/shipyard-core/',
  'seadrop/=lib/seadrop/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config